// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhriHsy1VaRvYH8ZMmCREvgc5DlSa8eE',
    appId: '1:151091445433:web:25ab78b819f5efb4976568',
    messagingSenderId: '151091445433',
    projectId: 'bynryapp',
    authDomain: 'bynryapp.firebaseapp.com',
    storageBucket: 'bynryapp.appspot.com',
    measurementId: 'G-9VPTDV5VC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACPGBlONeYO8rzgiraCx35LZgB5V9kBx4',
    appId: '1:151091445433:android:28f2e476b237d93e976568',
    messagingSenderId: '151091445433',
    projectId: 'bynryapp',
    storageBucket: 'bynryapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqwXgwb7RK-HJz90fZF6AvMxHpGL4ZgU',
    appId: '1:151091445433:ios:ad608e9212e88baf976568',
    messagingSenderId: '151091445433',
    projectId: 'bynryapp',
    storageBucket: 'bynryapp.appspot.com',
    androidClientId: '151091445433-itp8o8p0co1r0r01kilp57v4k7t9hc3c.apps.googleusercontent.com',
    iosClientId: '151091445433-c3ajasjr3jcae84lt2obhuqoa448v7g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bynryv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqwXgwb7RK-HJz90fZF6AvMxHpGL4ZgU',
    appId: '1:151091445433:ios:ad608e9212e88baf976568',
    messagingSenderId: '151091445433',
    projectId: 'bynryapp',
    storageBucket: 'bynryapp.appspot.com',
    androidClientId: '151091445433-itp8o8p0co1r0r01kilp57v4k7t9hc3c.apps.googleusercontent.com',
    iosClientId: '151091445433-c3ajasjr3jcae84lt2obhuqoa448v7g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bynryv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhriHsy1VaRvYH8ZMmCREvgc5DlSa8eE',
    appId: '1:151091445433:web:a64b52dd8c662e59976568',
    messagingSenderId: '151091445433',
    projectId: 'bynryapp',
    authDomain: 'bynryapp.firebaseapp.com',
    storageBucket: 'bynryapp.appspot.com',
    measurementId: 'G-8JFC5R1YCH',
  );

}